import { sql } from "drizzle-orm";
import {
  boolean,
  index,
  integer,
  jsonb,
  numeric,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

/**
 * The single source of table shape (blueprint §4). Two families:
 *   - MIRROR tables: read-only copies of Profit Plus. Written ONLY by the ingest
 *     (`src/lib/ingest/apply.ts`). Never edited from the app.
 *   - PORTAL-OWNED tables: carts, orders, proofs, users, sync bookkeeping.
 *
 * Better Auth's own tables (`user`, `session`, `account`, `verification`) are
 * generated by its CLI and migrated in E1-T6 — never redefined here.
 */

const nowTz = () => timestamp({ withTimezone: true }).notNull().defaultNow();

/* ------------------------------------------------------------------ mirror --- */

export const products = pgTable(
  "products",
  {
    coArt: text("co_art").primaryKey(), // RTRIM applied by the agent
    artDes: text("art_des").notNull(),
    coLin: text("co_lin"),
    coCat: text("co_cat"),
    coSubl: text("co_subl"),
    coProv: text("co_prov"),
    uniVenta: text("uni_venta"),
    precVta1: numeric("prec_vta1", { precision: 18, scale: 5 }).notNull(),
    stockAct: numeric("stock_act", { precision: 18, scale: 3 })
      .notNull()
      .default("0"),
    stockCom: numeric("stock_com", { precision: 18, scale: 3 })
      .notNull()
      .default("0"),
    anulado: boolean("anulado").notNull().default(false),
    campo1: text("campo1"), // CPE (registro sanitario)
    rowIdHex: text("row_id_hex").notNull(),
    syncedAt: timestamp("synced_at", { withTimezone: true }).notNull(),
  },
  (t) => [
    index("idx_products_anulado_co_lin").on(t.anulado, t.coLin),
    index("idx_products_art_des_fts").using(
      "gin",
      sql`to_tsvector('spanish', ${t.artDes})`,
    ),
  ],
);

export const productOverrides = pgTable("product_overrides", {
  coArt: text("co_art")
    .primaryKey()
    .references(() => products.coArt, { onDelete: "cascade" }),
  isHidden: boolean("is_hidden").notNull().default(false),
  photoUrl: text("photo_url"),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const customers = pgTable("customers", {
  coCli: text("co_cli").primaryKey(),
  cliDes: text("cli_des").notNull(),
  rif: text("rif"),
  email: text("email"),
  telefonos: text("telefonos"),
  descGlob: numeric("desc_glob", { precision: 6, scale: 3 })
    .notNull()
    .default("0"), // cascade position 4
  montCre: numeric("mont_cre", { precision: 18, scale: 2 })
    .notNull()
    .default("0"),
  saldo: numeric("saldo", { precision: 18, scale: 2 }).notNull().default("0"),
  plazPag: integer("plaz_pag").notNull().default(0),
  sincredito: boolean("sincredito").notNull().default(false),
  coSeg: text("co_seg"), // segment: 10=A 20=B 30=C 40=D 60=NUEVO 70=EXCLUIDOS
  tipo: text("tipo"), // target of oferta_cli (position 2)
  cond1pct: boolean("cond_1pct").notNull().default(false),
  inactivo: boolean("inactivo").notNull().default(false),
  rowIdHex: text("row_id_hex").notNull(),
  syncedAt: timestamp("synced_at", { withTimezone: true }).notNull(),
});

export const offers = pgTable(
  "offers",
  {
    coOfer: text("co_ofer").primaryKey(),
    oferDes: text("ofer_des").notNull(),
    posOfer: integer("pos_ofer").notNull(), // 0 = provider (p1), 1 = drugstore (p3)
    fecInic: timestamp("fec_inic", { withTimezone: true }).notNull(),
    fecFin: timestamp("fec_fin", { withTimezone: true }).notNull(),
    coSegD: text("co_seg_d"),
    coSegH: text("co_seg_h"),
    coCliD: text("co_cli_d"),
    coCliH: text("co_cli_h"),
    syncedAt: timestamp("synced_at", { withTimezone: true }).notNull(),
  },
  (t) => [index("idx_offers_vigencia").on(t.fecInic, t.fecFin, t.posOfer)],
);

export const offerLines = pgTable(
  "offer_lines",
  {
    coOfer: text("co_ofer")
      .notNull()
      .references(() => offers.coOfer, { onDelete: "cascade" }),
    coArt: text("co_art").notNull(),
    porcOfer: numeric("porc_ofer", { precision: 6, scale: 3 }).notNull(),
    syncedAt: timestamp("synced_at", { withTimezone: true }).notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.coOfer, t.coArt] }),
    index("idx_offer_lines_co_art").on(t.coArt),
  ],
);

export const customerOffers = pgTable("customer_offers", {
  coOfer: text("co_ofer").primaryKey(),
  oferDes: text("ofer_des").notNull(),
  fecInic: timestamp("fec_inic", { withTimezone: true }).notNull(),
  fecFin: timestamp("fec_fin", { withTimezone: true }).notNull(),
  tipoD: text("tipo_d"),
  tipoH: text("tipo_h"),
  coCliD: text("co_cli_d"),
  coCliH: text("co_cli_h"),
  syncedAt: timestamp("synced_at", { withTimezone: true }).notNull(),
});

export const customerOfferLines = pgTable(
  "customer_offer_lines",
  {
    coOfer: text("co_ofer")
      .notNull()
      .references(() => customerOffers.coOfer, { onDelete: "cascade" }),
    coCli: text("co_cli").notNull(),
    porcOfer: numeric("porc_ofer", { precision: 6, scale: 3 }).notNull(),
    syncedAt: timestamp("synced_at", { withTimezone: true }).notNull(),
  },
  (t) => [primaryKey({ columns: [t.coOfer, t.coCli] })],
);

export const productCaps = pgTable("product_caps", {
  coArt: text("co_art").primaryKey(),
  porcMax: numeric("porc_max", { precision: 6, scale: 3 }).notNull(),
  syncedAt: timestamp("synced_at", { withTimezone: true }).notNull(),
});

export const exchangeRate = pgTable("exchange_rate", {
  id: integer("id").primaryKey(), // always 1
  usdBs: numeric("usd_bs", { precision: 18, scale: 6 }).notNull(),
  effectiveAt: timestamp("effective_at", { withTimezone: true }).notNull(),
  syncedAt: timestamp("synced_at", { withTimezone: true }).notNull(),
});

/* ------------------------------------------------------------- portal-owned --- */

export const syncState = pgTable("sync_state", {
  source: text("source").primaryKey(),
  lastRowIdHex: text("last_row_id_hex").notNull().default("0x0000000000000000"),
  lastRunAt: timestamp("last_run_at", { withTimezone: true }),
  lastStatus: text("last_status"),
});

export const ingestEvents = pgTable("ingest_events", {
  eventId: text("event_id").primaryKey(),
  source: text("source").notNull(),
  receivedAt: nowTz(),
  rowsApplied: integer("rows_applied").notNull(),
});

export const appUsers = pgTable(
  "app_users",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    // Links to Better Auth user.id (table created in E1-T6). Nullable so an
    // admin-provisioned, contactless client exists before its identity is bound.
    authUserId: text("auth_user_id"),
    coCli: text("co_cli").references(() => customers.coCli, {
      onDelete: "restrict",
    }),
    role: text("role").notNull().default("client"), // 'client' | 'admin'
    createdAt: nowTz(),
  },
  (t) => [
    uniqueIndex("uq_app_users_co_cli").on(t.coCli),
    uniqueIndex("uq_app_users_auth").on(t.authUserId),
  ],
);

export const carts = pgTable(
  "carts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    appUserId: uuid("app_user_id")
      .notNull()
      .references(() => appUsers.id, { onDelete: "cascade" }),
    status: text("status").notNull().default("open"), // 'open' | 'submitted'
    createdAt: nowTz(),
    updatedAt: nowTz(),
  },
  (t) => [index("idx_carts_app_user_id").on(t.appUserId)],
);

export const cartLines = pgTable(
  "cart_lines",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    cartId: uuid("cart_id")
      .notNull()
      .references(() => carts.id, { onDelete: "cascade" }),
    coArt: text("co_art").notNull(),
    qty: numeric("qty", { precision: 18, scale: 3 }).notNull(),
  },
  (t) => [uniqueIndex("uq_cart_lines_cart_co_art").on(t.cartId, t.coArt)],
);

export const orders = pgTable(
  "orders",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orderNumber: text("order_number").notNull(),
    appUserId: uuid("app_user_id")
      .notNull()
      .references(() => appUsers.id, { onDelete: "restrict" }),
    coCli: text("co_cli").notNull(),
    usdBsUsed: numeric("usd_bs_used", { precision: 18, scale: 6 }).notNull(),
    applied1pct: boolean("applied_1pct").notNull().default(false),
    subtotal: numeric("subtotal", { precision: 18, scale: 2 }).notNull(),
    total: numeric("total", { precision: 18, scale: 2 }).notNull(),
    status: text("status").notNull().default("submitted"), // 'submitted' | 'imported'
    createdAt: nowTz(),
  },
  (t) => [
    uniqueIndex("uq_orders_number").on(t.orderNumber),
    index("idx_orders_app_user_id").on(t.appUserId),
  ],
);

export const orderLines = pgTable(
  "order_lines",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orderId: uuid("order_id")
      .notNull()
      .references(() => orders.id, { onDelete: "restrict" }),
    coArt: text("co_art").notNull(),
    artDes: text("art_des").notNull(), // snapshot
    qty: numeric("qty", { precision: 18, scale: 3 }).notNull(),
    precVta1: numeric("prec_vta1", { precision: 18, scale: 5 }).notNull(), // snapshot
    cascade: text("cascade").notNull(), // "p1+p2+p3+p4" (Profit format)
    unitFrozen: numeric("unit_frozen", { precision: 18, scale: 5 }).notNull(),
    lineNet: numeric("line_net", { precision: 18, scale: 2 }).notNull(),
  },
  (t) => [index("idx_order_lines_order_id").on(t.orderId)],
);

export const paymentProofs = pgTable(
  "payment_proofs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    appUserId: uuid("app_user_id")
      .notNull()
      .references(() => appUsers.id, { onDelete: "restrict" }),
    coCli: text("co_cli").notNull(),
    amount: numeric("amount", { precision: 18, scale: 2 }).notNull(),
    currency: text("currency").notNull(), // 'BS' | 'USD'
    method: text("method").notNull(), // 'transfer' | 'pago_movil' | 'deposit'
    reference: text("reference").notNull(),
    imageUrl: text("image_url").notNull(),
    note: text("note"),
    emailedAt: timestamp("emailed_at", { withTimezone: true }),
    createdAt: nowTz(),
  },
  (t) => [index("idx_payment_proofs_app_user_id").on(t.appUserId)],
);

export const auditLog = pgTable("audit_log", {
  id: uuid("id").primaryKey().defaultRandom(),
  actor: text("actor"),
  action: text("action").notNull(),
  targetType: text("target_type"),
  targetId: text("target_id"),
  metadata: jsonb("metadata"),
  createdAt: nowTz(),
});
